version: "3.8"
services:
  backend:
    container_name: koajs_mongodb
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/koajs
    volumes:
      - "./src:/app/src"
      - /app/node_modules
    networks:
      - trandung
  mongo:
    image: mongo:5.0.5
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - trandung
volumes:
  mongodbdata:
networks:
  trandung: